trigger:
- main

pool:
  name: MyAgents   # 👈 self-hosted pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME_21_X64)'   # 👈 points to your JDK 21 installation
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
